// <copyright file="GlobalSuppressions.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "@ symbol not related to localization", Scope = "member", Target = "~M:Gallery.Program.ConsoleCommands.AddPerson(Gallery.Logic.PersonLogic,System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Passing format string as parameter makes code hard to read", Scope = "member", Target = "~M:Gallery.Program.ConsoleCommands.ListAllPaintings(Gallery.Logic.Classes.GalleryLogic,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Passing format string as parameter makes code hard to read", Scope = "member", Target = "~M:Gallery.Program.ConsoleCommands.ListAllPeople(Gallery.Logic.PersonLogic,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Passing format string as parameter makes code hard to read", Scope = "member", Target = "~M:Gallery.Program.ConsoleCommands.ListAllExhibits(Gallery.Logic.Classes.GalleryLogic,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Passing format string as parameter makes code hard to read", Scope = "member", Target = "~M:Gallery.Program.ConsoleCommands.GetOneExhibit(Gallery.Logic.Classes.GalleryLogic,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Passing format string as parameter makes code hard to read", Scope = "member", Target = "~M:Gallery.Program.ConsoleCommands.GetOnePerson(Gallery.Logic.PersonLogic,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Passing format string as parameter makes code hard to read", Scope = "member", Target = "~M:Gallery.Program.ConsoleCommands.GetOnePainting(Gallery.Logic.Classes.GalleryLogic,System.String,System.String)")]
